config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :themes
  resources :sections
  resources :paragraphs
  resources :exercises
  resources :tasks
  resources :steps
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :step
  belongs_to :section

  enum status: { inactive: 1, active: 2 }

  # scope :step, ->(step) { where(step:) }
  # scope :section, ->(section) { where(section:) }

  # scope :theoretical, ->(section) { where(section:) }
  # scope :practical, ->(step) { where(step:) }

  # def self.theoretical(section)
  #   where(section:)
  # end

  # def self.practical(step)
  #   where(step:)
  # end
end

app/models/paragraph.rb
class Paragraph < ApplicationRecord
  belongs_to :section
  has_many_attached :images
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :theme
  has_many :paragraphs
  has_many :exercises
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :task
  has_many :exercises
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :steps
end

app/models/theme.rb
class Theme < ApplicationRecord
  has_many :sections
  has_many :exercises, through: :sections
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  def new
    @exercise = Exercise.new
  end

  def index
    # @exercises = Exercise.where(status: 'active').joins(:step)
    @exercises = Exercise.where('step_id = ?',
                                params[:step_id]).or(Exercise.where('section_id=?',
                                                                    params[:section_id]))
  end

  def create
    @exercise = Exercise.new(exercise_params)
    step = Step.find(exercise_params[:step_id])

    if @exercise.save
      redirect_to exercises_path(step_id: step.id)
    else
      render 'new'
    end
  end

  def show
    @exercise = Exercise.find(params[:id])
  end

  private

  def exercise_params
    params.require(:exercise).permit(:exercise, :solution, :tag, :step_id, :section_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/paragraphs_controller.rb
class ParagraphsController < ApplicationController
  def new
    @paragraph = Paragraph.new
  end

  def create
    @paragraph = Paragraph.new(paragraph_params)
    if @paragraph.save
      redirect_to section_path(id: paragraph_params[:section_id])
    else
      render 'new'
    end
  end

  def edit
    @paragraph = Paragraph.find(params[:id])
  end

  def update
    @paragraph = Paragraph.find(params[:id])
    if @paragraph.update(paragraph_params)
      redirect_to section_path(id: paragraph_params[:section_id])
    else
      render 'edit'
    end
  end

  private

  def paragraph_params
    params.require(:paragraph).permit(:content, :section_id, images: [])
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def new
    @section = Section.new
  end

  def index
    @sections = Section.all
  end

  def create
    @section = Section.new(section_params)
    if @section.save
      redirect_to themes_path
    else
      render 'new'
    end
  end

  def show
    @section = Section.find(params[:id])
  end

  private

  def section_params
    params.require(:section).permit(:title, :theme_id)
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  def new
    @step = Step.new
  end

  def create
    @step = Step.new(step_params)
    if @step.save
      redirect_to tasks_path
    else
      render 'new'
    end
  end

  def show
    @step = Step.find(params[:id])
  end

  private

  def step_params
    params.require(:step).permit(:description, :solution, :task_id)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @task = Task.new
  end

  def index
    @tasks = Task.all
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_path
    else
      render 'new'
    end
  end

  def show
    @task = Task.find(params[:id])
  end

  private

  def task_params
    params.require(:task).permit(:title, :guideline)
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  def index
    @themes = Theme.includes(:sections)
  end

  def new
    @theme = Theme.new
  end

  def create
    @theme = Theme.new(theme_params)
    if @theme.save
      redirect_to themes_path
    else
      render 'new'
    end
  end

  def show
    @theme = Theme.find(params[:id])
  end

  private

  def theme_params
    params.require(:theme).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/section_helper.rb
module SectionHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/exercises/index.html.erb
<h1>Index of exercises</h1>
<% @exercises.each do |exercise| %><br>
<%= exercise.exercise %><br>
<%= exercise.status %>
<%= link_to 'See the solution', exercise_path(exercise)%><br>

<% end %>
<%= link_to 'Add an exercise', new_exercise_path(step_id: params[:step_id])%>

app/views/exercises/new.html.erb
<h1>Exercises#new</h1>
<p>Find me in app/views/exercises/new.html.erb</p>
<%= form_with model: @exercise do |f| %>
<%= f.hidden_field :step_id, value: params[:step_id]%>

<%= f.label :tag %><br>
<%= f.text_field :tag %><br>

<%= f.label :what_to_do %><br>
<%= f.text_area :exercise %><br>

<%= f.label :solution %><br>
<%= f.text_area :solution %><br>
<%= f.collection_select(:section_id, Section.all, :id, :title, {prompt: 'Select the section'})%>
<%= f. submit %>
<% end %>

app/views/exercises/show.html.erb
<h1>Exercises#show</h1>
<p>Find me in app/views/exercises/show.html.erb</p>

<h4><%= @exercise.tag %></h4><br>
<%= @exercise.solution %><br>

app/views/home/index.html.erb
<h1>Home#Index</h1>
<%= link_to 'Show theme', themes_path %>
<%= link_to 'Show tasks', tasks_path %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Doc</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/paragraphs/edit.html.erb
<h1>Edit paragraph</h1>
<%= form_with model: @paragraph do |f| %>
<%= f.hidden_field :section_id, value: params[:section_id]%>

<%= f.label :content %>
<%= f.rich_text_area :body%>

<%= f.label :add_image %>
<%= f.file_field :images, multiple: true %>

<%= f.submit %>
<% end %>

app/views/paragraphs/new.html.erb
<%= form_with model: @paragraph do |f| %>
<%= f.hidden_field :section_id, value: params[:section_id]%>

<%= f.label :content %>
<%= f.text_area :content%>

<%= f.label :add_image %>
<%= f.file_field :images, multiple: true %>

<%= f.submit %>
<% end %>

app/views/sections/index.html.erb
<h1>Section index</h1>
<% @sections.each do |section|%>
Section:<br>
<%= section.title %><br>
<% section.exercises.each do |exercise| %><br>
Exercise:<br>
<%= exercise.exercise %><br>
<%= exercise.status %><br>
<% end %>
<% end %>

app/views/sections/new.html.erb
<%= form_with model: @section do |f| %>
<%= f.hidden_field :theme_id, value: params[:theme_id]%>
<%= f.label :section %><br>
<%= f.text_field :title %><br>
<%= f.submit %><br>
<% end %>

app/views/sections/show.html.erb
<h1>Show content of the section</h1>
<% @section.paragraphs.each do |paragraph|%>
<%= paragraph.content %><br>
<% if paragraph.images.attached? %>
<%  paragraph.images.each do |image| %>
    <%= image_tag image.variant(resize_to_limit: [100, nil]) %><br>
 <% end %>
 
 <% end%>
 <%= link_to 'Edit paragraph', edit_paragraph_path(section_id: @section.id)%>
<% end %>
<%= link_to 'See exercises', exercises_path(section_id: @section.id) %>



<br>

<%= link_to 'Add a paragraph', new_paragraph_path(section_id: @section.id) %><br>

app/views/steps/new.html.erb
<h1>Steps#new</h1>
<p>Find me in app/views/steps/new.html.erb</p>
<%= form_with model: @step do |f| %>
<%= f.hidden_field :task_id, value: params[:task_id]%>
<%= f.label :description %>
<%= f.text_area :description %>
<%= f.label :solution %>
<%= f.text_area :solution %>
<%= f.submit %>
<% end %>

app/views/steps/show.html.erb
<h1>Step#show</h1>
Step description:
<%= @step.description %><br>

<%= link_to 'Add an exercise', new_exercise_path(step_id: @step.id)%>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
<p>Find me in app/views/tasks/index.html.erb</p>

<% @tasks.each do |task|%><br>
<h2>Task:</h2>
<%= task.title %><br>
<%= task.guideline %><br>
<%= link_to 'Steps to take', task_path(task)%>
<% end %>

app/views/tasks/new.html.erb
<h1>Tasks#new</h1>
<p>Find me in app/views/tasks/new.html.erb</p>
<%= form_with model: @task do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>

<%= f.label :guidline %>
<%= f.text_field :guideline%>
<%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>
Task title:<br>
<%= @task.title %><br>
<% @task.steps.each do |step| %><br>
Step description:
<%= step.description %><br>
<%= link_to 'Show step', step_path(step) %><br>
<%= link_to 'Solution', step_path(step) %><br>
<%= link_to 'Exercises', exercises_path(step_id: step.id) %><br>
<% end %>

<%= link_to 'Add a step', new_step_path(task_id: @task.id)%>

app/views/themes/index.html.erb
<h1>Themes index</h1>
<% @themes.each do |theme|%><br>
Theme:
<%= theme.title %><br>
Sections:<br>
<% theme.sections.each do |section| %>
<%= link_to section.title, section_path(section) %> |<br> 

<% end %><br>
<%= link_to 'Add a section', new_section_path(theme_id: theme.id) %><br>

<% end %><br>

<%= link_to 'Create theme', new_theme_path %>

app/views/themes/new.html.erb
<%= form_with model: @theme do |f| %>
<%= f.label :theme %><br>
<%= f.text_field :title %><br>

<%= f.submit %><br>

<% end %>